_commit: '9815413'
_src_path: gh:bswck/skeleton
author_username: bswck
docs: true
docs_slug: runtime-generics
email_address: bswck.dev@gmail.com
github_username: bswck
license_name: MIT
org_full_name: Bartosz Sławecki
package_name: runtime_generics
project_description: Reuse type arguments explicitly passed at runtime to a generic
    class before instantiating.
publish_on_pypi: true
pypi_project_description: Reuse type arguments explicitly passed at runtime to a generic
    class before instantiating.
pypi_project_name: runtime-generics
python_version: '3.8'
repo_name: runtime_generics
test_suite: true
use_precommit: true
visibility: public
