_commit: 0.0.2rc-125-ga2febcf
_src_path: gh:bswck/skeleton
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Reuse generic class type arguments at runtime.
docs: true
email: bswck.dev@gmail.com
github: bswck
license: MIT
package: runtime_generics
precommit: true
pypi: true
pypi_description: Reuse generic class type arguments at runtime.
pypi_project_name: runtime-generics
pypy: true
python: '3.8'
repo: runtime_generics
rtd: runtime-generics
tests: true
visibility: public
wip: false
