_commit: 0.0.2rc-244-g52a2805
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Reuse generic class type arguments at runtime.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: MIT
package: runtime_generics
precommit: true
pypi: true
pypi_description: Reuse generic class type arguments at runtime.
pypi_project: runtime-generics
pypy: true
python: '3.8'
python_until: ''
repo: runtime_generics
tests: true
tidelift: true
visibility: public
wip: false
