#!/usr/bin/env bash
# (C) bswck
# Manual alias for a long pre-commit command that does some real magic ✨
#
# Run this before pushing to ensure that the code is formatted and package locks
# are up-to-date. Pre-commit updates requirements-dev.txt in order to make sure that
# the CI environment can install the dev dependencies without Poetry.
#
# Usage:
# $ magic
echo "✨ Doing the magic ✨"
pre-commit run --all-files --hook-stage push