name: Tests

on: [push]

jobs:
  test:
    environment: test
    env:
      SMOKESHOW_GITHUB_STATUS_DESCRIPTION: CLI Coverage {coverage-percentage}
      SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 50
      SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-major-version: [3]
        python-minor-version: [8, 9, 10, 11, 12]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-major-version }}.${{ matrix.python-minor-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-major-version }}.${{ matrix.python-minor-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run tests
      run: >-
        coverage run -m pytest -v .
    - name: Report coverage
      run: |
        coverage report
        coverage html
    - name: Install smokeshow and upload coverage
      if: ${{ matrix.python-minor-version == 8 }}
      run: |
        pip install smokeshow
        smokeshow upload htmlcov/index.html
